package com.bawei.wangliyang.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.bawei.wangliyang.model.Dao.FenDao;
import com.bawei.wangliyang.model.Dao.ShopDao;

import com.bawei.wangliyang.database.FenDaoDao;
import com.bawei.wangliyang.database.ShopDaoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig fenDaoDaoConfig;
    private final DaoConfig shopDaoDaoConfig;

    private final FenDaoDao fenDaoDao;
    private final ShopDaoDao shopDaoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        fenDaoDaoConfig = daoConfigMap.get(FenDaoDao.class).clone();
        fenDaoDaoConfig.initIdentityScope(type);

        shopDaoDaoConfig = daoConfigMap.get(ShopDaoDao.class).clone();
        shopDaoDaoConfig.initIdentityScope(type);

        fenDaoDao = new FenDaoDao(fenDaoDaoConfig, this);
        shopDaoDao = new ShopDaoDao(shopDaoDaoConfig, this);

        registerDao(FenDao.class, fenDaoDao);
        registerDao(ShopDao.class, shopDaoDao);
    }
    
    public void clear() {
        fenDaoDaoConfig.clearIdentityScope();
        shopDaoDaoConfig.clearIdentityScope();
    }

    public FenDaoDao getFenDaoDao() {
        return fenDaoDao;
    }

    public ShopDaoDao getShopDaoDao() {
        return shopDaoDao;
    }

}
