package com.bawei.wangliyang.database;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.bawei.wangliyang.model.Dao.FenDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "FEN_DAO".
*/
public class FenDaoDao extends AbstractDao<FenDao, Void> {

    public static final String TABLENAME = "FEN_DAO";

    /**
     * Properties of entity FenDao.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property FenJson = new Property(0, String.class, "FenJson", false, "FEN_JSON");
    }


    public FenDaoDao(DaoConfig config) {
        super(config);
    }
    
    public FenDaoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"FEN_DAO\" (" + //
                "\"FEN_JSON\" TEXT);"); // 0: FenJson
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"FEN_DAO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, FenDao entity) {
        stmt.clearBindings();
 
        String FenJson = entity.getFenJson();
        if (FenJson != null) {
            stmt.bindString(1, FenJson);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, FenDao entity) {
        stmt.clearBindings();
 
        String FenJson = entity.getFenJson();
        if (FenJson != null) {
            stmt.bindString(1, FenJson);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public FenDao readEntity(Cursor cursor, int offset) {
        FenDao entity = new FenDao( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0) // FenJson
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, FenDao entity, int offset) {
        entity.setFenJson(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(FenDao entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(FenDao entity) {
        return null;
    }

    @Override
    public boolean hasKey(FenDao entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
