package com.bawei.wangliyang.database;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.bawei.wangliyang.model.Dao.ShopDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SHOP_DAO".
*/
public class ShopDaoDao extends AbstractDao<ShopDao, Void> {

    public static final String TABLENAME = "SHOP_DAO";

    /**
     * Properties of entity ShopDao.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property ShopJson = new Property(0, String.class, "ShopJson", false, "SHOP_JSON");
    }


    public ShopDaoDao(DaoConfig config) {
        super(config);
    }
    
    public ShopDaoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SHOP_DAO\" (" + //
                "\"SHOP_JSON\" TEXT);"); // 0: ShopJson
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SHOP_DAO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ShopDao entity) {
        stmt.clearBindings();
 
        String ShopJson = entity.getShopJson();
        if (ShopJson != null) {
            stmt.bindString(1, ShopJson);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ShopDao entity) {
        stmt.clearBindings();
 
        String ShopJson = entity.getShopJson();
        if (ShopJson != null) {
            stmt.bindString(1, ShopJson);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public ShopDao readEntity(Cursor cursor, int offset) {
        ShopDao entity = new ShopDao( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0) // ShopJson
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ShopDao entity, int offset) {
        entity.setShopJson(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(ShopDao entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(ShopDao entity) {
        return null;
    }

    @Override
    public boolean hasKey(ShopDao entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
